### ISSUE TITLE
authentication with servant-auth

### ISSUE THREAD

**Issue by marcosh** [tweag/servant-template#3]
use [servant-auth](https://hackage.haskell.org/package/servant-auth) to manage authentication for all the requests

**Comment by hughjfchen** [comment]
Could you give more details why this issue would be closed? Isn't delegate the authentication to a library a better idea?

**Comment by marcosh** [comment]
the package is currently using `servant-auth`. See https://github.com/tweag/servant-template/blob/b5598af43ff69160c6d8a59d5e4a1f23358b6410/package.yaml#L37

I don't remember precisely, but I guess the issue was closed because the feature got implemented

**Comment by hughjfchen** [comment]
Yeah,I just found this. I've thought it'd not implemented yet since there is no PR referencing to this issue.
