### ISSUE TITLE
Read configuration from the environment instead of file

### ISSUE THREAD

**Issue by cgeorgii** [tweag/servant-template#36]
The application currently breaks the [Twelve-Factor App rule about configuration](https://12factor.net/config), reading it from a file instead of the environment. Read the link for more info on the drawbacks of the current approach.

A more robust solution is to enable configuration from the environment on staging/production and CI and from a file for development and testing.

**Comment by aspiwack** [comment]
Sorry. But I'll be vetoing this idea. I don't agree with the reasoning in the link. Environment are much easier to get wrong, they are very hard to audit. Files can even be reloaded without exiting the application.

**Comment by hughjfchen** [comment]
Shall we support both? I believe we can read the config from environment and also from a file. With some libraries, like `envy` and `dotenv`, that would be easier. The reason asking to support reading config from environment is that `servant` applications usually would be deployed to a container platform(like a k8s cluster) as a backend service. And services in a container platform use environment variables as config.

**Comment by marcosh** [comment]
@hughjfchen yep, that could be a nice idea, supporting several ways of configuring an application. Then we could probably use a monoid instance on the configuration to manage configuration overrides.

Would you be interested in contributing this to the project?
